#!/bin/bash

[ "${TENANT_FRAMEWORK_LOG}" ] && LOG_FILE="${TENANT_FRAMEWORK_LOG}" || LOG_FILE="/home/tenant/output/tenant_framework.log"

# Print out a usage for the invoked method, and return a failure code
usage() {
    echo "Usage:"
    echo "$1"
    return 1
}

# Log to console and tee to the framework log
USAGE_INFRALOG="infralog [message]"
if [ "$1" ]; then
    echo "$(date) - $1" | tee -a "${LOG_FILE}"
else
    usage "${USAGE_INFRALOG}"
fi
