apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: demotask-run-scdi
  namespace: demo
spec:
  serviceAccountName: demo-svc
  taskSpec:
    steps:
    - name: demo-scdi 
      image: stacey-0.localdomain:30003/tcicd/demo:1.1
      script: |
        #!/bin/bash
        /home/stacey/invoke.sh
